name: "AMS AS621x Sensor Driver CI"

on:
  pull_request:
  workflow_dispatch:

jobs:
  driver:
    uses: catie-aq/zephyr_workflows/.github/workflows/driver.yml@main
    secrets:
      personal_access_token: ${{ secrets.CI_6TRON_ZEPHYR_RO }}
    with:
      path: "samples"
